### PR TITLE
fix(workflow): Fix multiple context leaks in `reuseV8Context` executor

### LINKED ISSUE #1476: [Bug] Reusable VM allows context leak due to global variable reassignment
### Describe the bug

When the `reuseV8Context` option is enabled, we freeze global objects to prevent modifications from leaking from one Workflow execution context to another one.

However, we do not prevent reassignment of global variables. And since context switching is based solely on global variable names, the engine will leave those reassigned global variable untouched.

For example, the following test fails:

```
export async function sharedGlobalReassignment(): Promise<[string, string]> {
  type ConsoleExtended = Console & { wfid: string };
  globalThis.console = { ...console, wfid: workflowInfo().workflowId } as ConsoleExtended;
  await sleep(1);
  return [workflowInfo().workflowId, (console as ConsoleExtended).wfid];
}

test('Shared global state', withReusableContext, async (t) => {
  const { createWorker, taskQueue, env } = t.context;
  const worker = await createWorker();
  await worker.runUntil(async () => {
    const [res1, res2] = await Promise.all([
      env.client.workflow.execute(sharedGlobalReassignment, { taskQueue, workflowId: randomUUID() }),
      env.client.workflow.execute(sharedGlobalReassignment, { taskQueue, workflowId: randomUUID() }),
    ]);
    t.deepEqual(res1[0], res1[1]);
    t.deepEqual(res2[0], res2[1]);
  });
});
```

Deleting a global variable also fails, as the variable "reappears" on the next context switch. For example, the following test fails:

```
export async function globalMutatorAndDestructor(): Promise<number> {
  const global = globalThis as { a?: number };
  global.a = (global.a || 0) + 1;
  await sleep(1);
  delete global.a;
  await sleep(1);
  global.a = (global.a || 0) + 1;
  return global.a;
}

test('Set then Delete a global property', withReusableContext, async (t) => {
  const { createWorker, taskQueue, env } = t.context;
  const worker = await createWorker();
  await worker.runUntil(async () => {
    const res = await env.client.workflow.execute(globalMutatorAndDestructor, { taskQueue, workflowId: randomUUID() });
    t.is(res, 1);
  });
});
```

### LINKED ISSUE #1592: [Bug] Reusable VM allows context leak due to global symbol properties
### Describe the bug

When the `reuseV8Context` option is enabled, the logic that swaps global variables in and out for a specific Workflow Execution only look at "regular" properties on `globalThis`, but ignores `symbol` properties. Symbol properties may therefore leak from one Workflow Execution to another.

In a [recent investigation](https://github.com/izakfilmalter/temporal-effect-oom), this was identified as the cause of a memory leak when using [Effect](https://github.com/Effect-TS/effect) in Workflow Code, as Effect was storing its own "global store" as a symbol property on `globalThis`. Though this specific case has just been [fixed on Effect's side](https://github.com/Effect-TS/effect/pull/4196), we recognize that there was nothing wrong in them using global symbol properties this way, and that other libraries are likely to do so. We must therefore ensure that Temporal SDK is able to properly handle global symbol properties.

Huge thanks to @izakfilmalter for his work in preparing a repro project for this issue, capturing heap dumps, and coordinating efforts between Effect's and Temporal's teams, as well as to @mikearnaldi from [Effect](https://github.com/Effect-TS/effect) for his precious collaboration in investigating this through.

### PR DESCRIPTION
**Pull request by mjameswh**
## What was changed

- Fix multiple context leaks and bugs in the `reuseV8Context` executor:

  - …by reassigning a new object to an existing shared global variable: `globalThis.console = { ...globalThis.console, wfId: workflowInfo().workflowId }` (fixes #1476);

  - …by modifying one of Node's built in global objects: `globalThis.Number.a = workflowInfo().workflowId`;

  - …by deleting a previously set global variable: `globalThis.a = 1; await sleep(1) ; delete globalThis.a ; await sleep(1) ; globalThis.a = (globalThis.a || 0) + 1; /* globalThis.a is 2 rather than 1 */`

  - …by defining global symbol properties: `const mySymbol = Symbol.for('...'); globalThis[mySymbol] = ...` (fixes #1592).

Note: this is a second round over #1519. The code has changed considerably since the first previous review.

### CODE REVIEW

File: packages/common/src/type-helpers.ts [hunk 1]
```diff
@@ -219,23 +219,37 @@ export function SymbolBasedInstanceOfError<E extends Error>(markerName: string):
...
+// We also do not attempt to visit the prototype chain, as this would make it much harder to load
+// polyfills, and it is extremely unlikely anyway that one would modify the prototype of a built-in
+// object in a way that would have undesirable consequences (i.e. a polyfill function may actually
+// leak to another workflow context, but it wouldn't carry anything Workflow specific).
+export function deepFreeze<T>(object: T, visited = new WeakSet<any>()): T {
+  if (object == null || visited.has(object) || (typeof object !== 'object' && typeof object !== 'function'))
+    return object;
+  visited.add(object);
+  if (Object.isFrozen(object)) return object;
+
```
Comment (antlai-temporal) [inline packages/common/src/type-helpers.ts:237]: Can an object be frozen but not deepFrozen? If not, add a comment....

File: packages/test/src/test-reusev8context-perf.ts [hunk 2]
```diff
@@ -0,0 +1,170 @@
+// DONOTMERGE -- DO NOT REVIEW THIS FILE
+
```
Comment (antlai-temporal) [inline packages/test/src/test-reusev8context-perf.ts:2]: Is this comment correct? Do you need to remove this file?

File: packages/worker/src/workflow/vm-shared.ts [hunk 3]
```diff
@@ -93,7 +97,29 @@ export function injectConsole(context: vm.Context): void {
...
+
+export function injectGlobals(context: vm.Context): void {
+  const globals = {
+    AsyncLocalStorage,
+    URL,
+    URLSearchParams,
+    assert,
+    TextEncoder,
+    TextDecoder,
+    AbortController,
```
Comment (antlai-temporal) [inline packages/worker/src/workflow/vm-shared.ts:117]: Do any of these need to be deep frozen, or we assume they won't be abused...?

**Review by antlai-temporal — APPROVED** [review]
It seems we don't deep freeze Sets and Maps. Is this a concern? Do we need to document this somehow?

**Comment by mjameswh** [comment]
> It seems we don't deep freeze Sets and Maps. Is this a concern? Do we need to document this somehow?

That limitation is documented in `deepFreeze()`'s typedoc. Not a concern at this point because there should be no instance of Map or Set in `globalThis` after V8 context initialization, nor directly in one of our preloaded modules (i.e. the SDK itself). I had previously added coverage for those because I used a Map as part of the V8 context swapping algorithm, but no longer need it.

File: packages/common/src/type-helpers.ts (hunk 1 above)
Comment (mjameswh) [reply packages/common/src/type-helpers.ts:237]: Not sure what needs to be clarified here. The official typedoc on `Object.freeze()` already indicates that freezing is shallow, and generally well known to advanced JS devs.

File: packages/worker/src/workflow/vm-shared.ts (hunk 3 above)
Comment (mjameswh) [reply packages/worker/src/workflow/vm-shared.ts:117]: They will get deep frozen at the same time as all other global variables, after loading the script.

**Comment by mjameswh** [comment]
I moved `deepFreeze()` to `reusable-vm.ts` (rather than the `common` package) as some implementation decisions (e.g. freezing functions, not freezing prototypes, not handling Maps and Sets, etc) are specific to the Reusable VM Workflow Sandbox use case, and may not be appropriate for other use cases. It therefore doesn't seem appropiate to consider this as a reusable utility function.
