### PR TITLE
fix(worker): Fix prometheus and otel regressions

### LINKED ISSUE #1342: [Bug] Runtime fails to start with OtelCollectorExporter configured
### What are you really trying to do?
I updated to the latest typescript SDK 1.9.0 and the worker is failing to start with the `OtelCollectorExporter` settings enabled. 

### Describe the bug
When calling `Runtime.install` the worker crashes with the following error. Passing in an empty `headers` map seems to work but the parameter is labeled optional and was not required in the previous SDK version. 
```
Failed to build otlp exporter options: UninitializedField("headers")
TypeError: Failed to build otlp exporter options: UninitializedField("headers")
     at /Users/kirill/src/sparta/node_modules/@temporalio/core-bridge/index.js:16:14
     at Function.create (/Users/kirill/src/sparta/node_modules/@temporalio/worker/src/runtime.ts:206:31)
     at Function.install (/Users/kirill/src/sparta/node_modules/@temporalio/worker/src/runtime.ts:179:17)
     at runWorker (/Users/kirill/src/sparta/packages/api/src/entrypoints/TemporalWorker.ts:305:11)
     at start (/Users/kirill/src/sparta/packages/api/src/entrypoints/TemporalWorker.ts:517:9)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Minimal Reproduction
This fails
```
  Runtime.install({
    telemetryOptions: {
      metrics: {
        otel: {
          metricsExportInterval: '60s',
          url: 'grpc://0.0.0.0:4316',
        },
      },
    },
  });
```
This works
```
  Runtime.install({
    telemetryOptions: {
      metrics: {
        otel: {
          metricsExportInterval: '60s',
          url: 'grpc://0.0.0.0:4316',
          headers: {}
        },
      },
    },
  });
```

### Environment/Versions
- OS and processor: M1 Mac
- Temporal Version: typescript 1.9.0

### PR DESCRIPTION
**Pull request by mjameswh**
## What changed

- Fix `Runtime.install()` failing with error `Failed to build otlp exporter options: UninitializedField("headers")` when configuring OTEL metric exporter is configured without specifying headers (fix #1342).
- Fix Rust panic + TS hanging when trying to create a Worker if `Runtime` has been configured with Prometheus metrics exporter, but the specified port is already taken.
- Add more TS side tests related to Prometheus and OTEL metric exports.

- Also fix incorrect reporting `Ignoring WorkerOptions.interceptors.workflowModules because WorkerOptions.workflowBundle is set. To use workflow interceptors with a workflowBundle, pass them in the call to bundleWorkflowCode.`

### CODE REVIEW

File: packages/core-bridge/src/runtime.rs [hunk 1]
```diff
@@ -386,7 +398,18 @@ pub fn runtime_new(mut cx: FunctionContext) -> JsResult<BoxedRuntime> {
     let channel = Arc::new(cx.channel());
     let (sender, mut receiver) = unbounded_channel::<RuntimeRequest>();
 
-    std::thread::spawn(move || start_bridge_loop(telemetry_options, channel, &mut receiver));
+    // FIXME: This is a temporary fix to get sync notifications of errors while initializing the runtime.
```
Comment (Sushisource) [inline packages/core-bridge/src/runtime.rs:401]: Seems fine for now

File: packages/core-bridge/src/runtime.rs [hunk 2]
```diff
@@ -386,7 +398,18 @@ pub fn runtime_new(mut cx: FunctionContext) -> JsResult<BoxedRuntime> {
...
+    //        can simply yeild back a Result. But early attempts to do just that caused panics
+    //        on runtime shutdown, so let's use this hack until we can dig deeper.
+    let (result_sender, mut result_receiver) = unbounded_channel::<Result<(), String>>();
+
+    std::thread::spawn(move || start_bridge_loop(telemetry_options, channel, &mut receiver, result_sender));
+
+    if let Some(Err(e)) = result_receiver.blocking_recv() {
+        Err(cx.throw_error::<_, String>(e).unwrap_err())?;
+    }
+    result_receiver.close();
```
Comment (Sushisource) [inline packages/core-bridge/src/runtime.rs:412]: You don't need to explicitly close this.

Alternatively, you could use a oneshot channel

**Review by Sushisource — APPROVED** [review]
