### PR TITLE
fix!: Improve failure details, fixes #462

### LINKED ISSUE #462: [Bug] Put more info into workflow activation failures
## Problem

Currently, an Error thrown from a workflow results in this Worker output (& Web history):

```ts
throw new Error('error in workflow');
// Failing workflow activation...
// { message: "Error: error in workflow", source: "TypeScriptSDK", stack_trace: "", cause: None, failure_info: None }
```

And throwing an object results in:

```ts
throw { field: 'data' };
// Failing workflow activation...
// { message: "[object Object]", source: "TypeScriptSDK", stack_trace: "", cause: None, failure_info: None }
```

### Correct

- `failure_info`: Should be None in Error case. Use [subclass of `TemporalFailure`](https://docs.temporal.io/docs/typescript/handling-failure/#failure-classes-reference) to get this filled in.

### Change

- `message`: If thrown object isn't an Error, set `message = JSON.stringify(object)`. 
- `stack_trace`: Fill it in when Error is thrown (currently only filled in when `instanceof TemporalFailure`). When non-Error is thrown, log warning saying "we recommend throwing Errors so that you can see the stack trace".
- `cause`: When thrown error has a `cause` property, put a `Failure` here (currently only works when provided to constructor of `TemporalFailure` etc)
- `source`: Maybe be more specific, like `TypeScriptSDK > Worker > myWorkflowName`

## Related

@Sushisource We can't do anything about `throw new Error(object)`, since Node calls `toString()` on it before we get it:

image

image

### PR DESCRIPTION
**Pull request by lorensr**
Implements all I suggested in #462  except for more specific `source`, which I think would require passing more info to `errorToFailure`. I'd like to get to that later.

This change could be breaking: if a user is checking whether `failure.message === 'Error: orig message'`, it won't catch the new `failure.message = 'orig message'`. I think the old behavior that added the `Error: ` was unintentional—at the end of `errorToFailure`, the `instanceof Error` failed because the Error was coming from the vm, so `String(err)` was used.

### CODE REVIEW

File: packages/common/src/failure.ts [hunk 1]
```diff
@@ -329,15 +329,22 @@ export async function errorToFailure(err: unknown, dataConverter: DataConverter)
...
 
+  const stackTrace = `A non-Error value was thrown from your code. We recommend throwing Error objects so that we can provide a stack trace.`;
+
   if (typeof err === 'string') {
-    return { ...base, message: err };
+    return { ...base, stackTrace, message: err };
   }
 
-  return { ...base, message: String(err) };
+  return { ...base, stackTrace, message: JSON.stringify(err) };
```
Comment (bergundy) [inline packages/common/src/failure.ts:347]: I guess this is better in most cases

File: packages/common/src/failure.ts [hunk 2]
```diff
@@ -329,15 +329,22 @@ export async function errorToFailure(err: unknown, dataConverter: DataConverter)
...
+  if (isRecord(err) && hasOwnProperties(err, ['message', 'stack'])) {
+    return {
+      ...base,
+      message: String(err.message) ?? '',
+      stackTrace: cutoffStackTrace(String(err.stack)),
+      cause: await optionalErrorToOptionalFailure(err.cause, dataConverter),
+    };
   }
 
+  const stackTrace = `A non-Error value was thrown from your code. We recommend throwing Error objects so that we can provide a stack trace.`;
```
Comment (bergundy) [inline packages/common/src/failure.ts:341]: Not sure I'd use this as the stack trace because it's not formatted like one, consider putting this in the message.

File: packages/common/src/failure.ts [hunk 3]
```diff
@@ -329,15 +329,22 @@ export async function errorToFailure(err: unknown, dataConverter: DataConverter)
     source: FAILURE_SOURCE,
   };
 
-  if (err instanceof Error) {
-    return { ...base, message: err.message ?? '', stackTrace: cutoffStackTrace(err.stack) };
+  if (isRecord(err) && hasOwnProperties(err, ['message', 'stack'])) {
```
Comment (bergundy) [inline packages/common/src/failure.ts:332]: Why not check `instanceof Error`?

File: packages/common/src/failure.ts [hunk 4]
```diff
@@ -329,15 +329,22 @@ export async function errorToFailure(err: unknown, dataConverter: DataConverter)
...
+    return {
+      ...base,
+      message: String(err.message) ?? '',
+      stackTrace: cutoffStackTrace(String(err.stack)),
+      cause: await optionalErrorToOptionalFailure(err.cause, dataConverter),
```
Comment (bergundy) [inline packages/common/src/failure.ts:337]: Until this change `cause` was only used for chaining TemporalFailures, I don't know if we chain error causes in the other SDKs and if we should.

File: packages/common/src/failure.ts (hunk 3 above)
Comment (lorensr) [reply packages/common/src/failure.ts:332]: `err instanceof Error` is false when the Workflow does `throw new Error('unhandled rejection');`. Could also be helpful in the rare case of people throwing error-like objects

File: packages/common/src/failure.ts (hunk 4 above)
Comment (lorensr) [reply packages/common/src/failure.ts:337]: I haven't found where in Go SDK workflow errors are handled, but in Java, looks like `Error`s are rethrown and other non-specific throwables are wrapped in `WorkflowServiceException` with the throwable as the `cause`:

https://github.com/temporalio/sdk-java/blob/b0199150b69bb5a4eaf6c13ba4b89c2a8746a113/temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java#L299-L326

I'm not sure whether uniformity is important here? I figure we have a `cause` field, and might as well use it, as it could be helpful for users who are catching and throwing new non-`ApplicationFailure`s and want to include the original error as a cause. It will probably become a more common pattern (was added to v8 last year).

Comment (bergundy) [reply packages/common/src/failure.ts:337]: It will become popular I suspect, now it requires node > 16.9 AFAIK.

Let's keep it, sounds like a good addition to me.

File: packages/common/src/failure.ts [hunk 5]
```diff
@@ -329,15 +329,22 @@ export async function errorToFailure(err: unknown, dataConverter: DataConverter)
...
 
+  const recommendation = ` [A non-Error value was thrown from your code. We recommend throwing Error objects so that we can provide a stack trace.]`;
+
   if (typeof err === 'string') {
-    return { ...base, message: err };
+    return { ...base, message: err + recommendation };
   }
 
-  return { ...base, message: String(err) };
+  return { ...base, message: JSON.stringify(err) + recommendation };
```
Comment (Sushisource) [inline packages/common/src/failure.ts:347]: :tada:

**Review by Sushisource — APPROVED** [review]

**Comment by bergundy** [comment]
@lorensr make sure you sign into buildkite (you probably need an account) so all tests can run and we don't have to force merge.
In the near future, I'd like to have our own GH actions builders so we can drop BuildKite altogether.

**Comment by lorensr** [comment]
The issue isn't whether I had an account, but that I'm working on a fork. Should I check this?

image

**Comment by bergundy** [comment]
> The issue isn't whether I had an account, but that I'm working on a fork. Should I check this?
> 
> image

I think this applies to GH actions only. Afaik  buildkite works for forks, @Sushisource could probably answer that, I’d need to check but I can’t atm.

**Comment by lorensr** [comment]
Screenshot is from https://buildkite.com/temporal/typescript-sdk/settings/repository 
I was just wondering if it's unchecked for a security reason.

image

File: packages/common/src/failure.ts (hunk 3 above)
Comment (bergundy) [reply packages/common/src/failure.ts:332]: Oh, that makes sense because the `Error` is constructed in isolate context and converted into failure outside of that. We should probably work around it and ask the workflow to convert to a failure since it has an instance of the user's data converter.

**Review by bergundy — APPROVED** [review]
Just one comment, not anything too critical.
Keep it in mind when working on custom DC.

File: packages/common/src/failure.ts (hunk 3 above)
Comment (lorensr) [reply packages/common/src/failure.ts:332]: By moving this `errorToFailure`:

https://github.com/temporalio/sdk-typescript/blob/0488e8a74fa78c44d9fcad6e2631c7aae868aae5/packages/worker/src/workflow/vm.ts#L196

to here, instead of throwing? 

https://github.com/temporalio/sdk-typescript/blob/0488e8a74fa78c44d9fcad6e2631c7aae868aae5/packages/workflow/src/internals.ts#L504
