### PR TITLE
fix: Use error constructor name as `applicationFailureInfo.type`

### LINKED ISSUE #637: [Bug] Fix non-TemporalFailure type
### Describe the bug

We say that we set a failure's `type` [to the exception full type name when it doesn't extend TemporalFailure](https://typescript.temporal.io/api/classes/common.applicationfailure). However, `throw new MyFailure()`, where `MyFailure extends Error`, results in `type: 'Error'`:

image

It should be `type: 'MyFailure'`

### PR DESCRIPTION
**Pull request by vkarpov15**
## What was changed

Use `err.constructor.name` instead of `err.name` by default, since `.name` is still 'Error' for classes that extend Error.

## Checklist

1. Closes #637

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Review by bergundy — APPROVED** [review]
Nice, thanks!

File: packages/common/src/failure.ts [hunk 1]
```diff
@@ -357,7 +357,8 @@ export function ensureTemporalFailure(err: unknown): TemporalFailure {
   if (err instanceof TemporalFailure) {
     return err;
   } else if (err instanceof Error) {
-    const failure = new ApplicationFailure(err.message, err.name, false);
+    const name = err.constructor?.name || err.name;
```
Comment (bergundy) [inline packages/common/src/failure.ts:360]: Should we even use `err.name` anymore? Probably makes sense not to.

Comment (vkarpov15) [reply packages/common/src/failure.ts:360]: @bergundy I think it can't hurt to have it as a fallback. You can overwrite `constructor`:

```
const err = new Error('test');
err.constructor = null;
err.constructor?.name; // undefined
```

Comment (bergundy) [reply packages/common/src/failure.ts:360]: Yeah, but I wouldn't care about this too much TBH.
I'd probably change this to `err.construtor.name ?? 'Error'`

**Review by bergundy — APPROVED** [review]
@vkarpov15 I'll take over this PR and get it merged.

File: packages/common/src/failure.ts (hunk 1 above)
Comment (bergundy) [reply packages/common/src/failure.ts:360]: You know what, let's default to `err.name` as you suggested, looks like it should inherit from `Error`.
