### PR TITLE
fix(workflow)!: Make breakpoints work inside workflow isolate context

### LINKED ISSUE #795: [Bug] Breakpoints do not work for workflow code
Due to bundling of workflow code, it's impossible to set breakpoints on code that runs in workflow context.

There used to be a workaround for this before stack trace query was implemented by setting a `debugger` statement at the top of a workflow function but since that change we no longer inline the source-maps making it impossible to locate the source of the bundled code.

@mjameswh discovered that by setting a file name on the vm script we use to compile the code and having the file and source map available (on disk and possibly HTTP URL) the debugger can map back to the source and breakpoint work again.

Our proposed solution is to start an HTTP server in the worker when running in debug mode to serve the source map.
We'd debated whether to use http URLs or save the source map to a temporary directory and decided to go with HTTP since that will enable access when debugging remotely (for example when running a worker in a docker container).
The security implications of running an HTTP server in debug mode are minimal since a server has to be started regardless for the debugger to connect to the process.
The port to listen on should be configurable to enable remote access, if it is not provided, the server will listen on a random port.

### PR DESCRIPTION
**Pull request by mjameswh**
## Objective
Makes it possible to actually use breakpoints in workflow code.

## What was changed
- Use inline source maps
- Set script filename to be an absolute path, matching the original filename stored in the source map
- Make sure different workflow bundles get different filename
- Preload and cache the script object

## Checklist
1. Closes #795
2. How was this tested:
- Breakpoints during tests execution (vscode)
- Verdaccio build on local examples (vscode)
- Verdaccio build on local examples (chrome's debugger)

## Other notes
- Chrome's debugger don't know much about nodejs worker threads. It however works properly when running a worker in single thread mode (ie. `debugMode = true`)

### CODE REVIEW

File: packages/worker/src/workflow/bundler.ts [hunk 1]
```diff
@@ -95,16 +94,15 @@ export class WorkflowCodeBundler {
     // Cast because the type definitions are inaccurate
     const memoryFs = memfs.createFsFromVolume(vol);
     ufs.use(memoryFs as any).use({ ...realFS, readdir: readdir as any });
-    const distDir = '/dist';
+    const distDir = '/dist'; // FIXME: Make it possible for user to specify destination path
```
Comment (bergundy) [inline packages/worker/src/workflow/bundler.ts:97]: This would require writing to the real FS as well

File: packages/worker/src/worker.ts [hunk 2]
```diff
@@ -441,11 +440,11 @@ export class Worker {
   }
 
   protected static async createWorkflowCreator(
-    bundle: WorkflowBundleWithSourceMap,
+    bundle: WorkflowBundleAndCodePath,
     compiledOptions: CompiledWorkerOptions
   ): Promise<WorkflowCreator> {
     if (compiledOptions.debugMode) {
-      return await VMWorkflowCreator.create(bundle.code, bundle.sourceMap, compiledOptions.isolateExecutionTimeoutMs);
+      return await VMWorkflowCreator.create(bundle.code, bundle.codePath, compiledOptions.isolateExecutionTimeoutMs);
```
Comment (bergundy) [inline packages/worker/src/worker.ts:447]: Wouldn't the path be encoded in the bundle's source map?

File: packages/worker/src/worker-options.ts [hunk 3]
```diff
@@ -9,26 +9,25 @@ import { Runtime } from './runtime';
...
-  sourceMapPath: string;
 }
-export type WorkflowBundleOption = WorkflowBundleWithSourceMap | WorkflowBundlePathWithSourceMap;
+export type WorkflowBundleOption = WorkflowBundle | WorkflowBundlePath;
 
-export function isCodeBundleOption(bundleOpt: WorkflowBundleOption): bundleOpt is WorkflowBundleWithSourceMap {
+export function isCodeBundleOption(bundleOpt: WorkflowBundleOption): bundleOpt is WorkflowBundle {
   const opt = bundleOpt as any; // Cast to access properties without TS complaining
-  return typeof opt.code === 'string' && typeof opt.sourceMap === 'string';
+  return typeof opt.code === 'string';
```
Comment (bergundy) [inline packages/worker/src/worker-options.ts:25]: How do we extract the path from this?

File: packages/worker/src/workflow/vm.ts [hunk 4]
```diff
@@ -158,11 +158,10 @@ export class VMWorkflowCreator implements WorkflowCreator {
   public static async create<T extends typeof VMWorkflowCreator>(
     this: T,
     code: string,
-    sourceMap: string,
+    codePath: string | undefined,
```
Comment (bergundy) [inline packages/worker/src/workflow/vm.ts:161]: Doesn't look like this is used

File: packages/worker/src/workflow/vm.ts [hunk 5]
```diff
@@ -256,7 +255,27 @@ export class VMWorkflowCreator implements WorkflowCreator {
       });
     }
 
-    return new this(script, sourceMap, isolateExecutionTimeoutMs) as InstanceType<T>;
+    return new this(script, isolateExecutionTimeoutMs) as InstanceType<T>;
+  }
+
+  private static async makeScriptWithSourceMap(code: string) {
```
Comment (bergundy) [inline packages/worker/src/workflow/vm.ts:261]: Might as well make this protected in case anyone wants to extend this (granted we won't provide API safety for protected members)

File: packages/worker/src/workflow/vm.ts [hunk 6]
```diff
@@ -256,7 +255,27 @@ export class VMWorkflowCreator implements WorkflowCreator {
...
+    const sourceMappingUrlDataRegex = /\s*\n[/][/][#]\s+sourceMappingURL=data:(?:[^,]*),([^\s]+)\s*$/m;
```
Comment (bergundy) [inline packages/worker/src/workflow/vm.ts:262]: You could probably restrict data to base64 only characters.

File: packages/worker/src/workflow/vm.ts [hunk 7]
```diff
@@ -256,7 +255,27 @@ export class VMWorkflowCreator implements WorkflowCreator {
...
+
+      const filename = `/temporal/${sourceMapParsed.file}`;
+      const script = new vm.Script(code, { filename });
+      const sourceMapConsumer = await new SourceMapConsumer(sourceMapParsed);
+
+      return { script, filename, sourceMapConsumer };
+    } else {
+      const filename = `/temporal/workflowbundle-${uuid4()}.js`;
+      const script = new vm.Script(code, { filename });
+      return { script, filename, sourceMapConsumer: undefined };
```
Comment (bergundy) [inline packages/worker/src/workflow/vm.ts:277]: When would you expect this to happen? Wondering if we should emit an error here.

File: packages/worker/src/workflow/vm.ts (hunk 5 above)
Comment (bergundy) [reply packages/worker/src/workflow/vm.ts:261]: Could use some comments in this function

File: packages/worker/src/workflow/vm.ts [hunk 8]
```diff
@@ -256,7 +255,27 @@ export class VMWorkflowCreator implements WorkflowCreator {
...
+
+  private static async makeScriptWithSourceMap(code: string) {
+    const sourceMappingUrlDataRegex = /\s*\n[/][/][#]\s+sourceMappingURL=data:(?:[^,]*),([^\s]+)\s*$/m;
+    const sourceMapMatcher = code.match(sourceMappingUrlDataRegex);
+
+    if (sourceMapMatcher) {
+      const sourceMap = Buffer.from(sourceMapMatcher[1], 'base64').toString();
+      const sourceMapParsed: RawSourceMap = JSON.parse(sourceMap);
+
+      const filename = `/temporal/${sourceMapParsed.file}`;
```
Comment (bergundy) [inline packages/worker/src/workflow/vm.ts:269]: Why `/temporal`?

File: packages/worker/src/workflow/vm.ts (hunk 7 above)
Comment (mjameswh) [reply packages/worker/src/workflow/vm.ts:277]: I don’t expect this to happen if the user has correctly followed the bundling process, except for bundles that will have been produced with 1.0.1 and will be run on 1.0.2 without being rebundled (Which isn’t safe anyway…)

But I still need to deal with this case somehow. I’d be willing though to go with a throw new Error(…) if you are ok with it

File: packages/worker/src/workflow/bundler.ts [hunk 9]
```diff
@@ -221,11 +219,11 @@ export { api };
       },
       entry: [entry],
       mode: 'development',
-      devtool: 'source-map',
+      devtool: 'inline-source-map',
       output: {
+        pathinfo: true,
```
Comment (mjameswh) [inline packages/worker/src/workflow/bundler.ts:224]: Note to myself: not sure if this is rquired

File: packages/worker/src/workflow/bundler.ts (hunk 1 above)
Comment (mjameswh) [reply packages/worker/src/workflow/bundler.ts]: I removed the comment. The use case for this isn't clear enough. It would complexify the API and yet, there would be no guarantee that the file would actually be loaded from the same path location as it was created initially. For the same reason, I removed all references to `codePath` in other files.

File: packages/worker/src/worker.ts (hunk 2 above)
Comment (mjameswh) [reply packages/worker/src/worker.ts]: Same

File: packages/worker/src/workflow/vm.ts (hunk 7 above)
Comment (bergundy) [reply packages/worker/src/workflow/vm.ts:278]: In that case it could make sense to extract this in the main Node.js thread so the error could be caught by the user (would also save some (insignificant amount of?) work because right now we run this code once per worker thread.

File: packages/worker/src/worker.ts [hunk 10]
```diff
@@ -569,11 +564,8 @@ export class Worker {
       if (isCodeBundleOption(compiledOptions.workflowBundle)) {
         return compiledOptions.workflowBundle;
       } else if (isPathBundleOption(compiledOptions.workflowBundle)) {
-        const [code, sourceMap] = await Promise.all([
-          fs.readFile(compiledOptions.workflowBundle.codePath, 'utf8'),
-          fs.readFile(compiledOptions.workflowBundle.sourceMapPath, 'utf8'),
-        ]);
-        return { code, sourceMap };
+        const code = await fs.readFile(compiledOptions.workflowBundle.codePath, 'utf8');
```
Comment (bergundy) [inline packages/worker/src/worker.ts:567]: Does it matter if we use the path here as name of the vm script?

File: packages/worker/src/workflow/vm.ts (hunk 8 above)
Comment (bergundy) [reply packages/worker/src/workflow/vm.ts:270]: I think this will be a problem on windows.

File: packages/worker/src/workflow/vm.ts (hunk 7 above)
Comment (mjameswh) [reply packages/worker/src/workflow/vm.ts:278]: That's actually something I was considering... I'd probably move this to `getOrCreateBundle()`. What I'm unsure is what exactly should then be transferred to threads (ie. through `postMessage`)... Would it be reasonable (performance, memory...) to pass `sourceMapParsed` through the messaging port?

Comment (bergundy) [reply packages/worker/src/workflow/vm.ts:278]: The raw source map is transferrable, it's just a plain JS object.

File: packages/worker/src/workflow/vm.ts (hunk 8 above)
Comment (mjameswh) [reply packages/worker/src/workflow/vm.ts]: After more testing, it is much more reliable if I use `cwd()`. That also resolve the Windows concern.

File: packages/worker/src/worker.ts (hunk 10 above)
Comment (mjameswh) [reply packages/worker/src/worker.ts:570]: At this point, I don't think supporting this use case is worth delaying a release.
But should we want to do it, this would probably require rewriting the content of the `sourceMapURL` so that the filename matches the actual file.

File: packages/test/src/test-workflows.ts [hunk 11]
```diff
@@ -10,6 +10,7 @@ import { msToTs } from '@temporalio/internal-workflow-common';
 import { coresdk } from '@temporalio/proto';
 import { WorkflowCodeBundler } from '@temporalio/worker/lib/workflow/bundler';
 import { VMWorkflow, VMWorkflowCreator } from '@temporalio/worker/lib/workflow/vm';
+import { parseWorkflowCode } from '@temporalio/worker/src/worker';
```
Comment (bergundy) [inline packages/test/src/test-workflows.ts:13]: We typically import from lib, I guess for tests it doesn’t matter though

File: packages/worker/src/worker.ts (hunk 10 above)
Comment (bergundy) [reply packages/worker/src/worker.ts:570]: Sounds like it shouldn’t matter

File: packages/worker/src/worker.ts [hunk 12]
```diff
@@ -1648,6 +1643,38 @@ export class Worker {
...
+    // Context has not been properly configured, so eventual errors are possible. Just ignore at this point
+  }
+  preloadedScriptAndContext = [script, context];
+
+  return { code, sourceMap, filename };
+}
+
+// Keep these objects from GC. Otherwise the debugger risks source mapping resolution errors
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+let preloadedScriptAndContext: [vm.Script, unknown];
```
Comment (bergundy) [inline packages/worker/src/worker.ts:1676]: What happens if multiple bundles are loaded?
Can we store this in a worker attribute?

File: packages/worker/src/workflow/bundler.ts (hunk 9 above)
Comment (bergundy) [reply packages/worker/src/workflow/bundler.ts:224]: Want to check?

**Review by bergundy — APPROVED** [review]
Approving but I would like to see if there’s a way to get rid of the global script and context, maybe just store on the worker for now?
Wondering why it’s needed and if there’s a way around it.

File: packages/worker/src/worker.ts (hunk 10 above)
Comment (mjameswh) [reply packages/worker/src/worker.ts:570]: > I would like to see if there’s a way to get rid of the global script and context, maybe just store on the worker for now?
> Wondering why it’s needed and if there’s a way around it.

The issue is that parsing of the source map is done by the debugger (ie. in VS Code's process), concurrently with the execution of the workflow code (ie. node's process). Parsing the source map takes some time, and is associated with the vm context in which the script was discovered. Once parsing is completed, the debugger informs node about file mappings that it has discovered, _with the associated script id and context id_. Now, if that context has already been garbaged collected at that point (which is very likely with workflows since activations are very short lived and workflow bundles tends to be rather large), then node throws an error, ignoring file mappings provided by the debugger.

Adding preload and caching of the script and context has decreased breakpoints misses from over 9 out of 10 in some test scenarios to no miss at all. Workflow breakpoints are simply not reliable without this.

We can indeed attach the objects to the worker instead of keeping it in a global variable, and that was actually my original intent. Another possibility I'm considering at the moment is to attach the objects to a 10 seconds timer. That is more than enough to let the debugger completes parsing. I will have to look at vscode's debugger trace log however to determine if this cause errors at some later point.

I also observed that preloading is more reliable if performed _before_ worker threads are started, rather that once in worker threads. For example, I had cases where only one or two threads (over 8) would hit breakpoints, until disable and reenable all breakpoints. Looking at a trace from vscode's debugger, it looks like the debugger attaches some listeners to newly created threads, so my hypothesis is that the debugger might miss some type of events if they happens very early after thread creation.

**Comment by mjameswh** [comment]
> I would like to see if there’s a way to get rid of the global script and context, maybe just store on the worker for now?
> Wondering why it’s needed and if there’s a way around it.

The issue is that parsing of the source map is done by the debugger (ie. in VS Code's process), concurrently with the execution of the workflow code (ie. node's process). Parsing the source map takes some time, and is associated with the vm context in which the script was discovered. Once parsing is completed, the debugger informs node about file mappings that it has discovered, _with the associated script id and context id_. Now, if that context has already been garbaged collected at that point (which is very likely with workflows since activations are very short lived and workflow bundles tends to be rather large), then node throws an error, ignoring file mappings provided by the debugger.

Adding preload and caching of the script and context has decreased breakpoints misses from over 9 out of 10 in some test scenarios to no miss at all. Workflow breakpoints are simply not reliable without this.

We can indeed attach the objects to the worker instead of keeping it in a global variable, and that was actually my original intent. Another possibility I'm considering at the moment is to attach the objects to a 10 seconds timer. That is more than enough to let the debugger completes parsing. I will have to look at vscode's debugger trace log however to determine if this cause errors at some later point.

I also observed that preloading is more reliable if performed _before_ worker threads are started, rather that once in worker threads. For example, I had cases where only one or two threads (over 8) would hit breakpoints, until disable and reenable all breakpoints. Looking at a trace from vscode's debugger, it looks like the debugger attaches some listeners to newly created threads, so my hypothesis is that the debugger might miss some type of events if they happens very early after thread creation.

File: packages/worker/src/worker.ts (hunk 10 above)
Comment (mjameswh) [reply packages/worker/src/worker.ts:570]: My intuition also tells me that it should not matter (after all, the code being executed gave that source map, so why would we care about the name of the file), but experimentation tells me that setting breakpoints from the UI doesn't work unless the file name stored inside the source map exactly matches the script's filename.

TBH, that's not a big thing to fix. I'm just concerned that it might delay a release. Your call.

Comment (mjameswh) [reply packages/worker/src/worker.ts:570]: Done.

File: packages/worker/src/worker.ts (hunk 12 above)
Comment (mjameswh) [reply packages/worker/src/worker.ts]: Moved this to a 10 seconds timer. That's well enough for the debugger to parse the source and fully attach to the node process.

File: packages/worker/src/worker.ts [hunk 13]
```diff
@@ -1649,6 +1644,46 @@ export class Worker {
...
+  if (codePath) {
+    sourceMap.file = filename;
+    const patchedSourceMapJson = Buffer.from(JSON.stringify(sourceMap)).toString('base64');
+    const fixedSourceMappingUrl = `\n//# sourceMappingURL=data:application/json;base64,${patchedSourceMapJson}`;
+    code = code.slice(0, -sourceMapMatcher[1].length) + fixedSourceMappingUrl;
+  }
+
+  // Preloading the script makes breakpoints significantly more reliable and more responsive
+  // Keep these objects from GC long enough for debugger to complete parsing the source map and reporting locations
+  // to the node process. Otherwise, the debugger risks source mapping resolution errors, meaning breakings wont work.
```
Comment (lorensr) [inline packages/worker/src/worker.ts:1671]:
```suggestion
  // to the node process. Otherwise, the debugger risks source mapping resolution errors, meaning breakpoints won't work.
```

File: packages/worker/src/worker.ts [hunk 14]
```diff
@@ -1649,6 +1644,46 @@ export class Worker {
...
+
+  if (codePath) {
+    sourceMap.file = filename;
+    const patchedSourceMapJson = Buffer.from(JSON.stringify(sourceMap)).toString('base64');
+    const fixedSourceMappingUrl = `\n//# sourceMappingURL=data:application/json;base64,${patchedSourceMapJson}`;
+    code = code.slice(0, -sourceMapMatcher[1].length) + fixedSourceMappingUrl;
+  }
+
+  // Preloading the script makes breakpoints significantly more reliable and more responsive
+  // Keep these objects from GC long enough for debugger to complete parsing the source map and reporting locations
```
Comment (lorensr) [inline packages/worker/src/worker.ts:1670]: move this comment down to `setTimeout`?

File: packages/worker/src/worker.ts [hunk 15]
```diff
@@ -1649,6 +1644,46 @@ export class Worker {
   }
 }
 
+export interface WorkflowBundleWithSourceMap {
+  code: string;
+  sourceMap: RawSourceMap;
+  filename: string;
+}
+
+export function parseWorkflowCode(code: string, codePath?: string): WorkflowBundleWithSourceMap {
```
Comment (lorensr) [inline packages/worker/src/worker.ts:1653]: Could add automated test for this fn

**Review by lorensr — APPROVED** [review]

**Review by bergundy — APPROVED** [review]
