### PR TITLE
fix: Misc fixes related to older Node releases

### LINKED ISSUE #1063: [Bug] Temporal does not use standard AbortController/AbortSignal typings
### What are you really trying to do?

I am trying to pass `Context.current().cancellationSignal` to [`execa`](https://github.com/sindresorhus/execa) so child processes can be automatically killed when a workflow is cancelled.

### Describe the bug

TypeScript is not happy:

```
Argument of type 'import("/.../node_modules/abort-controller/dist/abort-controller").AbortSignal' is not assignable to parameter of type 'AbortSignal'.
Type 'AbortSignal' is missing the following properties from type 'AbortSignal': reason, throwIfAborted
```

Execa expects a standard library `AbortSignal` and Temporal is using a third-party `AbortSignal`.

### Additional context

I saw that ceab74d9d608a0f808cd2a9f63012064800f5044 introduced the `abort-controller` dependency for compatibility with Node 14 as `AbortController` was introduced in Node 15. Does the SDK have any official support policy? There have been two LTS releases since Node 14 (Node 16 and Node 18), both of which support AbortController. Can we just drop the `abort-controller` dependency and use the standard library?

### PR DESCRIPTION
**Pull request by mjameswh**
## What changed

- Completetly remove support for Node versions <= 14.17. Lot of our dependencies were already requiring Node 14.18+ anyway.
- Load package 'abort-controller' as a polyfill rather than a complete substitution. This will ensure using native implementation of that class in Node 16+ (fix #1063)
- Added the "node:" prefix on all of our Node built-in modules imports, except for files that might get loaded inside the Workflow sandbox.

### CODE REVIEW

File: packages/test/src/activities/cancellable-fetch.ts [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import fetch from 'node-fetch';
+import type { AbortSignal as FetchAbortSignal } from 'node-fetch/externals';
 import { Context } from '@temporalio/activity';
 
 export async function cancellableFetch(url: string): Promise<Uint8Array> {
-  const response = await fetch(url, { signal: Context.current().cancellationSignal });
+  const response = await fetch(url, { signal: Context.current().cancellationSignal as FetchAbortSignal });
```
Comment (bergundy) [inline packages/test/src/activities/cancellable-fetch.ts:6]: Sucks that we have to do this

File: packages/worker/src/workflow/vm-shared.ts [hunk 2]
```diff
@@ -356,13 +355,6 @@ export abstract class BaseVMWorkflow implements Workflow {
    */
   protected async tryUnblockConditions(): Promise<void> {
```
Comment (bergundy) [inline packages/worker/src/workflow/vm-shared.ts:356]: Doesn't need to be async anymore

**Review by bergundy — APPROVED** [review]
Had one minor comment.
Curious which tools have issues with the `node:` prefix, I would prefer to keep it if possible.

File: packages/test/src/activities/cancellable-fetch.ts (hunk 1 above)
Comment (mjameswh) [reply packages/test/src/activities/cancellable-fetch.ts:6]: I agree, but node-fetch intentionally redefine the `AbortSignal` interface to also include DOM WG's methods, so passing a standard Node 18 `AbortSignal` won't compile. We could technically go their way and redefine the `AbortSignal` interface to include these extra methods, but then we risk creating even more incompatibilities. I think this cast is the least bad option.

File: packages/worker/src/workflow/vm-shared.ts (hunk 2 above)
Comment (mjameswh) [reply packages/worker/src/workflow/vm-shared.ts:356]: Good catch

**Comment by mjameswh** [comment]
> Curious which tools have issues with the node: prefix

The only specific case I can trace back ATM was an outdated version of Jest, but I remember there have been some other cases (including Webpack under certain circonstances).

> I would prefer to keep it if possible

Why do you care? TBH I'm very slightly inclined to use the prefix, but at this point, we have not been using it consistently anyway.

**Comment by bergundy** [comment]
If we do go for consistency, I'd change it to be the other way around but I'm not religious about it.
Agree that being consistent is better.

**Comment by mjameswh** [comment]
>If we do go for consistency, I'd change it to be the other way around but I'm not religious about it. Agree that being consistent is better.

Fair enough. Added 'node:' prefix everywhere possible

**Comment by bergundy** [comment]
You should modify the PR description.
