### PR TITLE
fix(worker): Don't register errors more than once allowing for multiple module imports w/o panic

### LINKED ISSUE #469: [Bug] Allow registerErrors to be called multiple times
### What are you really trying to do?

Support users who run TS SDK worker code multiple times.

### Describe the bug

When `native.registerErrors(errors)` is run a second time, you get this error:

```
thread '<unnamed>' panicked at 'Must call `into_inner` or `drop` on `Root` https://docs.rs/neon/latest/neon/sync/index.html#drop-safety', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-0.8.3/src/handle/root.rs:182:13
stack backtrace:
   0:        0x113d2bd14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8483effd3e9ec544
   1:        0x113d45c0c - core::fmt::write::ha34752bcd39bca36
   2:        0x113d26304 - std::io::Write::write_fmt::hfc57a6e48a9ddae2
   3:        0x113d2d474 - std::panicking::default_hook::{{closure}}::he9aaba83dd453f35
   4:        0x113d2d054 - std::panicking::default_hook::hc87ff103cfd8260f
   5:        0x113d2dab4 - std::panicking::rust_panic_with_hook::hf890018b6cf19ef5
   6:        0x1135eb4bc - std::panicking::begin_panic::{{closure}}::hc28ceab4bf363482
   7:        0x1135eae34 - std::sys_common::backtrace::__rust_end_short_backtrace::h28965f507c5b3b3b
   8:        0x113d4df90 - std::panicking::begin_panic::hd003aa45410d163b
   9:        0x113666e88 - <neon::handle::root::Root<T> as core::ops::drop::Drop>::drop::h24d3c7b78d11aee1
  10:        0x11363f788 - temporal_sdk_typescript_bridge::errors::register_errors::h43400655bb40e232
  11:        0x1136d237c - neon::context::internal::Scope<R>::with::hf709c02593da6b84
  12:        0x11360845c - <neon::types::internal::FunctionCallback<T> as neon::types::internal::Callback<*mut neon_runtime::napi::bindings::types::Value__>>::invoke::he86aaaa185b14e07
Warning: neon::sync::Root leaked during a panic
 FAIL  tests/sequential/queues/addCronJob/producer.test.ts
  ● Test suite failed to run

    internal error in Neon module: Must call `into_inner` or `drop` on `Root` https://docs.rs/neon/latest/neon/sync/index.html#drop-safety

      at Object.<anonymous> (../../node_modules/@temporalio/worker/src/worker.ts:64:8)
      at Object.<anonymous> (../../node_modules/@temporalio/worker/src/index.ts:11:1)
```

Coming from: https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/worker/src/worker.ts#L64

### Minimal Reproduction

Can make, lmk if helpful.

### Environment/Versions

`@temporalio/worker@0.17.2`

### Additional context

Reported by user: https://temporalio.slack.com/archives/C01DKSMU94L/p1644200062345539

### PR DESCRIPTION
**Pull request by SamSokolin**
## What was changed

Currently if you import the `@temporalio/worker` module more than once, you run into a Rust panic because `native.registerErrors` is called once per import:
https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/worker/src/worker.ts#L64
and the underlying Rust `register_errors` function can only be called once:
https://github.com/temporalio/sdk-typescript/blob/2232465a4f9b0cade28f0c21c2d7856053678728/packages/core-bridge/src/errors.rs#L67

This PR adds a check to see if `register_errors` has been called already, and makes the function do nothing if it has.

## Why?

#469 

## Checklist

1. Closes #469 

2. How was this tested:
I made the changes locally and then pointed my project at my version of the Temporal Typescript SDK. I then ran the same sequential integration tests which were previously failing with the error in #469. Now the tests succeeded. 

3. Any docs updates needed?

N/a

### CODE REVIEW

File: packages/core-bridge/src/errors.rs [hunk 1]
```diff
@@ -65,6 +67,13 @@ impl CustomError for OnceCell<Root<JsFunction>> {
 /// It expects a single argument, an object with the various Error constructors.
 /// This is a very common pattern in Neon modules.
 pub fn register_errors(mut cx: FunctionContext) -> JsResult<JsUndefined> {
+    // Don't do anything if errors are already registered
```
Comment (bergundy) [inline packages/core-bridge/src/errors.rs:70]: Your solution is prone to races if this function is called concurrently.

I'd just use [`set`](https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html#method.set) here and early return on error.

Comment (SamSokolin) [reply packages/core-bridge/src/errors.rs:70]: Sounds good, will update

**Review by bergundy — APPROVED** [review]
